# Generated by Django 5.2.10 on 2026-01-17 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Epic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(help_text="Epic title", max_length=200)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Detailed description"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("TODO", "To Do"),
                            ("IN_PROGRESS", "In Progress"),
                            ("DONE", "Done"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="TODO",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="User who created this epic",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="epics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Epic",
                "verbose_name_plural": "Epics",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserStory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="User story title", max_length=200),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="User story details"),
                ),
                (
                    "as_a",
                    models.CharField(blank=True, help_text="As a...", max_length=100),
                ),
                (
                    "i_want",
                    models.CharField(
                        blank=True, help_text="I want to...", max_length=200
                    ),
                ),
                (
                    "so_that",
                    models.CharField(
                        blank=True, help_text="So that...", max_length=200
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("TODO", "To Do"),
                            ("IN_PROGRESS", "In Progress"),
                            ("DONE", "Done"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="TODO",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                    ),
                ),
                (
                    "story_points",
                    models.IntegerField(
                        blank=True,
                        help_text="Effort estimation (Fibonacci: 1, 2, 3, 5, 8, 13)",
                        null=True,
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="User assigned to this story",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_stories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "epic",
                    models.ForeignKey(
                        help_text="Epic this user story belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_stories",
                        to="tasks.epic",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Story",
                "verbose_name_plural": "User Stories",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(help_text="Task title", max_length=200)),
                ("description", models.TextField(blank=True, help_text="Task details")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("TODO", "To Do"),
                            ("IN_PROGRESS", "In Progress"),
                            ("DONE", "Done"),
                            ("BLOCKED", "Blocked"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="TODO",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                    ),
                ),
                (
                    "estimated_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Estimated hours to complete",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "actual_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Actual hours spent",
                        max_digits=5,
                        null=True,
                    ),
                ),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="User assigned to this task",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_story",
                    models.ForeignKey(
                        help_text="User story this task belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="tasks.userstory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Task",
                "verbose_name_plural": "Tasks",
                "ordering": ["-created_at"],
            },
        ),
    ]
