# Generated by Django 5.2.10 on 2026-01-17 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="epic",
            name="reporter",
            field=models.ForeignKey(
                blank=True,
                help_text="User who reported this epic",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reported_epics",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="reporter",
            field=models.ForeignKey(
                blank=True,
                help_text="User who reported this task",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reported_tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userstory",
            name="reporter",
            field=models.ForeignKey(
                blank=True,
                help_text="User who reported this story",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reported_stories",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
